"""Build inspectable FFmpeg media jobs."""

from flowmpeg import shortcuts
from flowmpeg.artifacts import (
    ArtifactKind,
    ArtifactSet,
    FrameSet,
    FrameWorkflow,
    ImageFormat,
    SegmentWorkflow,
    dash_package,
    frame_sequence,
    hls_package,
)
from flowmpeg.audit import (
    AUDIT_CODES,
    AuditConstraints,
    AuditFinding,
    AuditSummary,
    MediaAudit,
    audit_media,
)
from flowmpeg.batch import (
    BatchItemResult,
    BatchJob,
    BatchResult,
    BatchStatus,
    BatchWorkspace,
    CancellationToken,
    run_batch,
)
from flowmpeg.black import BlackInterval, BlackReport, detect_black
from flowmpeg.clip import Clip, concat_clips, media, replace_audio
from flowmpeg.comparison import (
    MediaComparison,
    MediaSummary,
    compare_media,
    compare_media_info,
)
from flowmpeg.crop_detection import CropCandidate, CropReport, detect_crop
from flowmpeg.errors import (
    BinaryNotFoundError,
    BinaryUnusableError,
    CompilationError,
    ExecutionError,
    FlowmpegError,
    GraphError,
    JobCancelledError,
    JobTimeoutError,
    OutputExistsError,
    ProbeError,
)
from flowmpeg.loudness import LoudnessMeasurement, measure_loudness
from flowmpeg.model import Expression, MediaGraph, StreamKind, expr
from flowmpeg.plan import OutputSpec, Plan, output
from flowmpeg.probe import (
    AudioStreamInfo,
    FormatInfo,
    MediaInfo,
    Rational,
    StreamInfo,
    SubtitleStreamInfo,
    VideoStreamInfo,
    probe,
    probe_raw,
)
from flowmpeg.progress import Progress
from flowmpeg.recipes.audio import (
    change_audio_speed,
    delay_audio,
    duck_audio,
    fade_audio,
    mix_audio,
    normalize_loudness,
    normalize_loudness_measured,
    trim_audio,
    volume,
)
from flowmpeg.recipes.video import (
    change_video_speed,
    crop_video,
    overlay_video,
    rotate_video,
    scale,
    stack_video,
    trim_video,
)
from flowmpeg.runner import RunResult, run
from flowmpeg.scenes import SceneChange, SceneReport, detect_scenes
from flowmpeg.silence import SilenceInterval, SilenceReport, detect_silence
from flowmpeg.streams import (
    AudioStream,
    MediaInput,
    SubtitleStream,
    VideoStream,
    apply_filter,
    input,
)
from flowmpeg.workflows import (
    LoudnessWorkflow,
    LoudnessWorkflowResult,
    normalize_loudness_two_pass,
)

__version__ = "0.1.0"

__all__ = [
    "AudioStream",
    "AudioStreamInfo",
    "ArtifactKind",
    "ArtifactSet",
    "AUDIT_CODES",
    "AuditFinding",
    "AuditConstraints",
    "AuditSummary",
    "BatchItemResult",
    "BatchJob",
    "BatchResult",
    "BatchStatus",
    "BatchWorkspace",
    "BinaryNotFoundError",
    "BinaryUnusableError",
    "BlackInterval",
    "BlackReport",
    "Clip",
    "CompilationError",
    "CancellationToken",
    "CropCandidate",
    "CropReport",
    "ExecutionError",
    "Expression",
    "FlowmpegError",
    "FormatInfo",
    "FrameSet",
    "FrameWorkflow",
    "GraphError",
    "JobCancelledError",
    "JobTimeoutError",
    "ImageFormat",
    "LoudnessMeasurement",
    "LoudnessWorkflow",
    "LoudnessWorkflowResult",
    "MediaGraph",
    "MediaInput",
    "MediaInfo",
    "MediaAudit",
    "MediaComparison",
    "MediaSummary",
    "OutputExistsError",
    "OutputSpec",
    "Plan",
    "ProbeError",
    "Progress",
    "Rational",
    "RunResult",
    "SceneChange",
    "SceneReport",
    "SegmentWorkflow",
    "SilenceInterval",
    "SilenceReport",
    "StreamKind",
    "StreamInfo",
    "SubtitleStream",
    "SubtitleStreamInfo",
    "VideoStream",
    "VideoStreamInfo",
    "__version__",
    "apply_filter",
    "audit_media",
    "change_audio_speed",
    "change_video_speed",
    "compare_media",
    "compare_media_info",
    "concat_clips",
    "crop_video",
    "delay_audio",
    "dash_package",
    "detect_black",
    "detect_crop",
    "detect_scenes",
    "detect_silence",
    "duck_audio",
    "expr",
    "fade_audio",
    "frame_sequence",
    "input",
    "hls_package",
    "media",
    "measure_loudness",
    "mix_audio",
    "normalize_loudness",
    "normalize_loudness_measured",
    "normalize_loudness_two_pass",
    "overlay_video",
    "output",
    "probe",
    "probe_raw",
    "replace_audio",
    "rotate_video",
    "run_batch",
    "run",
    "scale",
    "stack_video",
    "shortcuts",
    "trim_audio",
    "trim_video",
    "volume",
]
